package brain

import (
	"bytes"
	"context"
	"fmt"
	"strings"
	"time"
)

// Correlation is generated by Agent Brain and accompanies every task and
// gateway request. ContinuationID is optional and must never contain content.
type Correlation struct {
	TaskID         string `json:"task_id"`
	SessionID      string `json:"session_id"`
	RequestID      string `json:"request_id"`
	ContinuationID string `json:"continuation_id,omitempty"`
}

func (c Correlation) Validate() error {
	for name, value := range map[string]string{
		"task_id":    c.TaskID,
		"session_id": c.SessionID,
		"request_id": c.RequestID,
	} {
		if strings.TrimSpace(value) == "" {
			return fmt.Errorf("%s is required", name)
		}
	}
	return nil
}

// TaskRequest is the neutral task-routing contract. It carries intent only;
// provider credentials and account identities are forbidden.
type TaskRequest struct {
	Version         string      `json:"version"`
	Correlation     Correlation `json:"correlation"`
	CLIKind         CLIKind     `json:"cli_kind"`
	RouteModel      RouteModel  `json:"route_model"`
	RouterOwner     RouterOwner `json:"router_owner"`
	RoutePolicyID   string      `json:"route_policy_id"`
	GatewayRequired bool        `json:"gateway_required"`
}

func (r TaskRequest) Validate() error {
	if r.Version != ContractVersion {
		return fmt.Errorf("unsupported contract version %q", r.Version)
	}
	if err := r.Correlation.Validate(); err != nil {
		return err
	}
	if _, err := ParseCLIKind(string(r.CLIKind)); err != nil {
		return err
	}
	if _, err := ParseRouteModel(string(r.RouteModel)); err != nil {
		return err
	}
	if _, err := ParseRouterOwner(string(r.RouterOwner)); err != nil {
		return err
	}
	if strings.TrimSpace(r.RoutePolicyID) == "" {
		return fmt.Errorf("route policy id is required")
	}
	if r.GatewayRequired && r.RouterOwner != RouterOwnerOmniRoute {
		return fmt.Errorf("gateway-required task must have omniroute as its only router owner")
	}
	return nil
}

type TaskStatus string

const (
	TaskStatusCompleted          TaskStatus = "completed"
	TaskStatusFailed             TaskStatus = "failed"
	TaskStatusCancelled          TaskStatus = "cancelled"
	TaskStatusGatewayUnavailable TaskStatus = "gateway_unavailable"
	TaskStatusGatewayAuthFailed  TaskStatus = "gateway_authentication_failed"
	TaskStatusCapabilityRejected TaskStatus = "capability_rejected"
	TaskStatusOverloaded         TaskStatus = "overloaded"
)

type TaskResult struct {
	Correlation     Correlation           `json:"correlation"`
	Status          TaskStatus            `json:"status"`
	Retryable       bool                  `json:"retryable"`
	ErrorClass      string                `json:"error_class,omitempty"`
	InjectedFailure InjectedFailureMarker `json:"injected_failure,omitempty"`
}

// InjectedFailureMarker is the content-free I2 terminal classification. False
// identifies a real/non-injected failure; true identifies a synthetic failure
// injected by an authorized offline harness. A boolean deliberately prevents
// callers from attaching a reason, payload, identity, or other free-form data.
type InjectedFailureMarker bool

const (
	FailureReal              InjectedFailureMarker = false
	FailureSyntheticInjected InjectedFailureMarker = true
)

// UnmarshalJSON accepts only an explicit JSON boolean. An omitted field keeps
// the zero-value FailureReal classification, while null and every non-boolean
// JSON type fail closed without accepting caller-supplied content.
func (m *InjectedFailureMarker) UnmarshalJSON(data []byte) error {
	if m == nil {
		return fmt.Errorf("injected failure marker destination is nil")
	}
	*m = FailureReal
	switch string(bytes.TrimSpace(data)) {
	case "false":
		return nil
	case "true":
		*m = FailureSyntheticInjected
		return nil
	default:
		return fmt.Errorf("injected failure marker must be a JSON boolean")
	}
}

func (m InjectedFailureMarker) Validate(status TaskStatus) error {
	if !bool(m) {
		return nil
	}
	switch status {
	case TaskStatusFailed, TaskStatusGatewayUnavailable, TaskStatusGatewayAuthFailed, TaskStatusCapabilityRejected:
		return nil
	default:
		return fmt.Errorf("synthetic injected marker requires a terminal failure status")
	}
}

type RuntimeDescriptor struct {
	CLIKind CLIKind
	Path    string
}

type ModelCapability struct {
	RouteModel       RouteModel
	Protocol         ProtocolFamily
	Streaming        bool
	Tools            bool
	Reasoning        bool
	StructuredOutput bool
	ContextLimit     int
	ObservedAt       time.Time
}

// TaskExecutor owns cold-plane task execution and lifecycle only.
type TaskExecutor interface {
	Execute(context.Context, TaskRequest) (TaskResult, error)
}

// RuntimeRegistry resolves an executable by CLIKind only.
type RuntimeRegistry interface {
	ResolveRuntime(context.Context, CLIKind) (RuntimeDescriptor, error)
}

// GatewayReadinessChecker exposes fail-closed readiness without routing in Go.
type GatewayReadinessChecker interface {
	CheckGatewayReadiness(context.Context, ReadinessRequest) (ReadinessSnapshot, error)
}

// ModelCapabilityRegistry validates exact gateway model/protocol capabilities.
type ModelCapabilityRegistry interface {
	LookupModelCapability(context.Context, RouteModel) (ModelCapability, error)
}

// ResultSink receives redacted lifecycle results. It must never receive task
// content, repository content, tool payloads, reasoning, or credentials.
type ResultSink interface {
	PublishResult(context.Context, TaskResult) error
}
